package com.ck66.dusou.ui.theme

import androidx.compose.ui.graphics.Color

// Light theme — 淡紫色（基于弹窗截图校准）
val md_theme_light_primary = Color(0xFF7C5DBE)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFEDE4F8)
val md_theme_light_onPrimaryContainer = Color(0xFF1F0A4D)
val md_theme_light_secondary = Color(0xFF6B5B7E)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFEDE4F8)
val md_theme_light_onSecondaryContainer = Color(0xFF1F0A4D)
val md_theme_light_tertiary = Color(0xFF9575A8)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFF7EDF8)
val md_theme_light_onTertiaryContainer = Color(0xFF2D1A30)
val md_theme_light_background = Color(0xFFFDFAFF)
val md_theme_light_onBackground = Color(0xFF1D1B20)
val md_theme_light_surface = Color(0xFFFDFAFF)
val md_theme_light_onSurface = Color(0xFF1D1B20)
val md_theme_light_surfaceVariant = Color(0xFFEAE3F0)
val md_theme_light_onSurfaceVariant = Color(0xFF79747E)
val md_theme_light_error = Color(0xFFB3261E)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFF9DEDC)
val md_theme_light_onErrorContainer = Color(0xFF410E0B)
val md_theme_light_outline = Color(0xFF9C8FA8)
val md_theme_light_outlineVariant = Color(0xFFCCC4D3)

// Dark theme — 深色模式（淡紫反相）
val md_theme_dark_primary = Color(0xFFCFBAEC)
val md_theme_dark_onPrimary = Color(0xFF3D2466)
val md_theme_dark_primaryContainer = Color(0xFF5A3E8A)
val md_theme_dark_onPrimaryContainer = Color(0xFFEDE4F8)
val md_theme_dark_secondary = Color(0xFFCBC0E0)
val md_theme_dark_onSecondary = Color(0xFF332B45)
val md_theme_dark_secondaryContainer = Color(0xFF49415C)
val md_theme_dark_onSecondaryContainer = Color(0xFFEDE4F8)
val md_theme_dark_tertiary = Color(0xFFE0C8E8)
val md_theme_dark_onTertiary = Color(0xFF44284F)
val md_theme_dark_tertiaryContainer = Color(0xFF5D3E67)
val md_theme_dark_onTertiaryContainer = Color(0xFFF7EDF8)
val md_theme_dark_background = Color(0xFF141218)
val md_theme_dark_onBackground = Color(0xFFE6E0E9)
val md_theme_dark_surface = Color(0xFF1B1721)
val md_theme_dark_onSurface = Color(0xFFE6E0E9)
val md_theme_dark_surfaceVariant = Color(0xFF49454F)
val md_theme_dark_onSurfaceVariant = Color(0xFFCAC4D0)
val md_theme_dark_error = Color(0xFFF2B8B5)
val md_theme_dark_onError = Color(0xFF601410)
val md_theme_dark_errorContainer = Color(0xFF8C1D18)
val md_theme_dark_onErrorContainer = Color(0xFFF9DEDC)
val md_theme_dark_outline = Color(0xFF9C8FA8)
val md_theme_dark_outlineVariant = Color(0xFF49454F)
